#cloud-config

package_update: true
packages:
  - docker.io

runcmd:
- modprobe kvm
- docker run --rm --privileged --name mythril -d -u 0:0 -v /tmp:/tmp adamschwalm/hypervisor-build:13 sleep 900
- sleep 900 && systemctl poweroff
