name: Gcloud

on: [push, pull_request_target]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Start GCloud Instance
      run: |
        gcloud compute instances create ci-$GITHUB_RUN_ID --zone us-east1-b \
                --machine-type=n2-highcpu-4 \
                --image mythril-test-image-2 \
                --metadata-from-file user-data=cloud-config.yml
    - name: Wait until instance is ready
      timeout-minutes: 5
      run: |
        until gcloud compute ssh ci-$GITHUB_RUN_ID --quiet \
                      --zone us-east1-b --container mythril \
                      --command 'echo Connection established'
        do
          echo Connection failed. Waiting 5 seconds...
          sleep 5
        done
    - name: Run tests
      run: |
        gcloud compute ssh ci-$GITHUB_RUN_ID --quiet \
                --zone us-east1-b --container mythril --ssh-flag="-t" <<EOF
          mkdir mythril
          cd mythril
          git init
          git remote add origin https://github.com/mythril-hypervisor/mythril.git
          git fetch --depth 1 origin f173342a8d8bdffa63e813b87853b8724faad441
          git reset --hard FETCH_HEAD
          git submodule init
          git submodule update --depth 1
          make test
          exit
        EOF
    - name: Cleanup
      if: always()
      run: |
        gcloud compute instances delete --zone us-east1-b ci-$GITHUB_RUN_ID
