name: Gcloud

on: [push, pull_request_target]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Use gcloud CLI
      run: |
        gcloud compute instances create ci-$GITHUB_RUN_ID --zone us-east1-b \
                --min-cpu-platform "Intel Haswell" --machine-type=f1-micro \
                --image nested-vm-image
        gcloud compute ssh ci-$GITHUB_RUN_ID --quiet -- cat /proc/cpuinfo
    - name: Cleanup
      if: always()
      run: |
        gcloud compute instances delete ci-$GITHUB_RUN_ID
